# Version 5.0 config
version: 5.0
# Basic server configuration
port: 80
address: 127.0.0.1
logging: true
managePassword: changeme
# QoL improvements below this line
hideIpAddress: true
hideUserAgent: true
simplifiedLogging: false
hideGetFavicon: false
hideQueryString: true
clearConsoleOnStart: true